name: Pobieranie działek

on:
  schedule:
    - cron: "0 9 * * 1"   # w każdy poniedziałek o 9:00
  workflow_dispatch:       # pozwala uruchomić ręcznie

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python dzialki.py

      - name: Upload Excel artifact
        uses: actions/upload-artifact@v4
        with:
          name: dzialki-excel
          path: dzialki.xlsx
